initial import from private repo
nubank/umschreiben-clj pull request #1
Opened 2021-06-11 10:53 UTC by philomates

2021-06-11 12:27 UTC, gabrielgiussi commented on test/umschreiben_clj/requires_test.clj
> +  ;; I don't find a use case for this! unless we want to provide low-level functions that should be composed. But
This is from me, let's remove the comment and/or the test. Do you think the test makes sense?

2021-06-11 12:28 UTC, gabrielgiussi requested changes
Configure a github action to run the tests

2021-06-11 12:30 UTC, gabrielgiussi requested changes
Configure a github action to run the tests

2021-06-11 13:14 UTC, philomates commented
@gabrielgiussi I've updated things, good to go now?

2021-06-14 11:53 UTC, gabrielgiussi approved these changes

2021-06-14 11:54 UTC, merged